### ISSUE TITLE
console.dir works the same as log 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/ios-runtime#875] opened 2018-02-06 08:47 UTC
_From @NickIliev on November 13, 2017 11:34_

_From @NickIliev on October 30, 2017 7:41_

_From @Andy-ZYA on October 28, 2017 8:48_

I am following the [official tutorial](https://docs.nativescript.org/angular/tutorial/ng-chapter-1) and after I change console.log to console.dir, the terminal shows the same thing.

`CONSOLE LOG file:///app/app.component.js:6:20: [object Object]
CONSOLE LOG file:///app/tns_modules/@angular/core/./bundles/core.umd.js:2957:20: Angu`

How should I fix this problem?

_Copied from original issue: NativeScript/NativeScript#4997_

_Copied from original issue: NativeScript/nativescript-cli#3186_

_Copied from original issue: NativeScript/NativeScript#5064_

**Comment by Christopotamus** [comment] 2018-02-14 00:37
Is there an ETA on this bug? I can confirm this still happens to me on 3.4.1 ios only.

**Comment by ginev** [comment] 2018-02-16 09:42
@Christopotamus - we will make sure to include the fix for this behavior in the next major release.

**Closed** 2018-03-15 13:01 UTC
Labels: bug, os: ios

**Comment by Neutrino-Sunset** [comment] 2018-04-01 10:44
I get this bug to with Android on Mint 18.3

`┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.3           │ 3.4.3          │ Up to date    │
│ tns-core-modules │ 3.4.1           │ 3.4.1          │ Up to date    │
│ tns-android      │ 3.4.2           │ 3.4.2          │ Up to date    │
│ tns-ios          │                 │ 3.4.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘`

**Comment by Neutrino-Sunset** [comment] 2018-04-01 11:00
After modifying the app several times and tns run refreshing it, it started working.

**Comment by Natalia-Hristova** [comment] 2018-04-02 10:38
@Neutrino-Sunset , 
this issue is for `ios` and you said that you don't have it installed, so what's your specific steps to reproduce it? Probably you face something different?

Have in mind that this fix will be available in the next official release `4.0.0` (coming next week) or you can try it out right now with the `rc` version of `tns-ios`  --> `tns platform add ios@rc`. 
Please, let us know if you still encounter it with the `rc` version.

**Comment by aaayushsingh** [comment] 2018-04-10 07:30
I'm still getting this. I'm using ios simulator on mac

```
"tns-ios": {
			"version": "4.0.1-rc-2018-04-05-01"
}
```
CONSOLE LOG file:///app/main-page.js:16:16: [object Object]
CONSOLE LOG file:///app/other-page.js:1:82: other-page's console
CONSOLE LOG file:///app/other-page.js:13:14: [object Object]
CONSOLE LOG file:///app/other-page.js:18:16: [object Object]

**Comment by Natalia-Hristova** [comment] 2018-04-10 09:45
@aaayushsingh what's your version of `nativescript`?

**Comment by aaayushsingh** [comment] 2018-04-10 09:59
@Natalia-Hristova it's 3.4.3

**Comment by Natalia-Hristova** [comment] 2018-04-10 10:28
@aaayushsingh  the issue is also related with nativescript so you should update `nativescript` to `rc`. 
You can do it like this:
```
npm cache clean -f
npm uni -g nativescript
npm i -g nativescript@rc
```
Then remove ios platform and add it's `rc` version.
Thanks for your comment! I'll add this in the comment for the fix.

Please let me know if you still face the same issue after the update.

**Comment by aaayushsingh** [comment] 2018-04-11 06:56
@Natalia-Hristova Works now, thanks! 

There is no indenting though, everything is to the very left of the terminal. It's hard to find things, is it going to change before the release?

**Comment by aaayushsingh** [comment] 2018-04-11 08:40
I was talking about this behaviour highlighted in this image.

<img width="1176" alt="screen shot 2018-04-11 at 2 03 34 pm" src="https://user-images.githubusercontent.com/19550852/38605696-ae20fef6-3d91-11e8-90bc-231a572404ae.png">

 I can work on it and possibly submit a PR, just guide me to the part where I look for it and start working.

**Comment by Natalia-Hristova** [comment] 2018-04-11 09:42
Ohh , now I understand. You're right - definitely can be better

> I can work on it and possibly submit a PR, just guide me to the part where I look for it and start working.


Great! It would be super awesome!

First, you can start with environment setup -> [README.md](https://github.com/NativeScript/ios-runtime/blob/master/README.md) after that  you can check the [guidelines to follow when contributing](https://github.com/NativeScript/ios-runtime/blob/master/CONTRIBUTING.md) - CLA signing, branch management, etc and also read how to[ connect the local iOS runtime project to a custom {N} project for easier debugging]( 
https://docs.nativescript.org/runtimes/ios/how-to/debug-ios-runtime)

You can look at [this code](https://github.com/NativeScript/ios-runtime/blob/master/src/NativeScript/inspector/GlobalObjectConsoleClient.cpp#L51) to implement the fix you suggest.

Hope this will help you to start and soon you will became a part of the the {N} contributors family :)

If you have any questions or face any problems related to the setup or not, feel free to open a new issue so it would be easier to find it and to be resolved (instead of writing here in this issue).
