### ISSUE TITLE
Upgraded our OS to 14.2 and the enterprise app starts crashing, couldn't open it, install via MDM 

### ISSUE THREAD

**Issue by xiaohappyc** [NativeScript/ios-runtime#1286] opened 2020-12-01 09:16 UTC
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.3
 - Cross-platform modules:
 - iOS Runtime: 6.5.3
 - Android Runtime (if applicable):5.5.0
 - Plugin(s):

**Describe the bug**
https://developer.apple.com/forums/thread/666399
OS: iOS 14.2, iOS 14.3 Beta 1, iOS 14.3 Beta 2
Hardware: Any arm64e cpu device (ex: iPad Pro 11" 1st/2nd gen, iPad Pro 12.9" 3rd/4th gen, iPad 8th gen, iPad Air 3rd/4th gen, iPhone 11, etc)
Deployment:
Deployed via any MDM and AppStore, install via MDM -> crash,install via AppStore -> works fine,
Ad-hoc .ipa deployment works fine even via MDM,
so via -> AppStore -> MDM -> crash

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**
Does anyone have a similar problem? This is currently the same problem with Xamarin Apps.

**Comment by rigor789** [comment] 2020-12-01 11:00
Duplicate of #9079

**Closed by rigor789** 2020-12-01 11:00 UTC
