### ISSUE TITLE
Incorrect Class Conversion NSClassFromString()

### ISSUE THREAD

**Issue by kivlara** [NativeScript/ios-runtime#296] opened 2015-09-10 14:12 UTC
objc:
```objective-c
@interface AppDelegate : NSObject
...
@end

@implementation AppDelegate
...
@end
```

in javascript:
```javascript
console.log(NSClassFromString("AppDelegate"));
```
result:
```javascript
function NSObject() {
    [native code]
}
```
I think this is an error: need to be:
```javascript
function AppDelegate() {
    [native code]
}
```
I try to use an Objective C Class declared by me, in javascript but I can't access him.
I get:  ```JS ERROR ReferenceError: Can't find variable: AppDelegate```
so i try to get this class from NSClassFromString.

P.S: Thank you for an amazing product!

**Comment by jasssonpet** [comment] 2015-09-10 14:15
Hello,

You should add a `module.modulemap` (similar to this [one](https://github.com/NativeScript/ios-runtime-docs/blob/master/native-libs/CocoaPods.md#module-maps)) with the headers that you wish to be visible in NativeScript.

**Comment by kivlara** [comment] 2015-09-10 14:21
Thank you, I will try this one, 
but ```NSClassFromString()``` is working as expected ???
My approach was: 
if I can't get AppDelegate because of ```JS ERROR ReferenceError: Can't find variable: AppDelegate``` as direct call 
i try NSClassFromString("AppDelegate") but result was something unexpected.

**Comment by kivlara** [comment] 2015-09-10 14:30
Lets say this code:
```
@interface AppDelegate : NSObject
+(id)sharedInstance;
@end
```

if i do in javascript:
```
var cls = NSClassFromString("AppDelegate");
console.log(cls.sharedInstance());
```
I get:
```
+[NSObject sharedInstance]: unrecognized selector sent to class 0x19c28a0a0
```

**Comment by jasssonpet** [comment] 2015-09-10 14:36
Can you please share the contents of your module map?

**Comment by kivlara** [comment] 2015-09-10 15:25
I check what u ask and .m file is OK!
I check it calling:

``` NSLog(@"%@", NSClassFromString(@"AppDelegate"));```
result:
``` AppDelegate ```

second check: -----------------------------------------------------------------------
objc:
```NSLog(@"%@", [AppDelegate sharedInstance]);```
result: 
```<Fg5435fg: 0x1700301c0>```

javascript:
``` console.log(AppDelegate.sharedInstance()); ```
result:
``` JS ERROR ReferenceError: Can't find variable: AppDelegate ```

--------------------------------------------------------------------------------------------------------------------
```
module Test {
   umbrella header "Test.h"
   export *
}
```

**Comment by jasssonpet** [comment] 2015-09-10 15:30
It turns out that you'll have to add `$(PROJECT_DIR)/TestApp` to the `HEADER_SEARCH_PATHS` in the build settings, if your module map is in `platform/ios/TestApp`.

**Comment by kivlara** [comment] 2015-09-10 15:31
All ready.

If I right understand modulemap is needed for JS to know what class to expose in javascript and this data is embedded in metadata ??
How can I check this ??
May be there is some tool to check what is in metadata file ??

**Comment by jasssonpet** [comment] 2015-09-10 15:33
One easy way to do so is to check the metadata generator output. There should be something like: `Result: 25050 declarations from 88 top level modules`. After you add the module map, it should increase to `Result: 25051 declarations from 89 top level modules` for example.

**Comment by kivlara** [comment] 2015-09-10 15:46
Here is Generator Result:
```
Generating metadata for arm64:
Parsed header search paths:
"/Users/*******/Library/Developer/Xcode/DerivedData/Test-eqiftjqtxxibohcsejjruwsauwcv/Build/Products/Debug-iphoneos/include"
"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"
"/Users/*******/Library/Developer/Xcode/DerivedData/Test-eqiftjqtxxibohcsejjruwsauwcv/Build/Products/../IntermediateBuildFilesPath/UninstalledProducts/**"
Parsed framework search paths:
"/Users/*******/Library/Developer/Xcode/DerivedData/Test-eqiftjqtxxibohcsejjruwsauwcv/Build/Products/Debug-iphoneos"
"/Volumes/X/WORK/ObjC/Test/Test/**"
"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks"
Clang parameters: -v -x objective-c -fno-objc-arc -fmodule-maps -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -arch arm64 -target arm-apple-darwin -std=gnu99 -miphoneos-version-min=8.0 -Wno-unknown-pragmas -Wno-ignored-attributes -ferror-limit=0 -I/Users/*******/Library/Developer/Xcode/DerivedData/Test-eqiftjqtxxibohcsejjruwsauwcv/Build/Products/Debug-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/*******/Library/Developer/Xcode/DerivedData/Test-eqiftjqtxxibohcsejjruwsauwcv/Build/Products/../IntermediateBuildFilesPath/UninstalledProducts/** -F/Users/*******/Library/Developer/Xcode/DerivedData/Test-eqiftjqtxxibohcsejjruwsauwcv/Build/Products/Debug-iphoneos -F/Volumes/X/WORK/ObjC/Test/Test/** -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks 
Merged 399 categories.
Result: 23442 declarations from 79 top level modules
Done! Running time: 1.53535 sec 
```

**Comment by jasssonpet** [comment] 2015-09-10 15:53
If you add `$(PROJECT_DIR)/YOUR_APP_NAME` to the `HEADER_SEARCH_PATHS` there should be something like:
```
Parsed header search paths:
...
.../YOUR_APP_NAME/platforms/ios/YOUR_APP_NAME
```
in the output, which I don't seem to find in this output.

**Comment by kivlara** [comment] 2015-09-10 16:09
The problem is that i take your ios-runtime build a static .a lib and include it in my already working project, next i added precompile script ```cd $SRCROOT/Test/metadataGenerator/bin; sh metadata-generation-build-step.sh```

**Comment by kivlara** [comment] 2015-09-10 16:17
I checked ```$CONFIGURATION_BUILD_DIR``` and find ```umbrella-arm64.h``` and there are NO all my classes.

**Comment by kivlara** [comment] 2015-09-10 16:19
I will try to rewrite MetadataGenerator a bit, to show more info about this problem ..
but the problem with ```NSClassFromString()``` is opened.

**Comment by kivlara** [comment] 2015-09-10 18:08
I finally resolve problem with ```module.modulemap```
Now I have all my headers in ```umbrella-arm64.h```.
but when i try from JS to call ``` AppDelegate.sharedInstance(); ``` i get same error: ```JS ERROR ReferenceError: Can't find variable: AppDelegate ```

**Comment by jasssonpet** [comment] 2015-09-10 18:40
To view what metadata is generated, you can try setting the `-output-yaml existing_dir` in the metadata generation script among the other flags. After you build again, there should be a `Test.yaml` file with your interface in it.

**Comment by kivlara** [comment] 2015-09-10 18:46
OMG! Thank you. I finally solved all problems. The problem was that I have an ```#define``` but ```objc-metadata-generator``` generate before precompile. So i get umbiguous JS <-> ObjC.

**Comment by kivlara** [comment] 2015-09-10 18:47
Thank you! For help! But I have one more problem!

**Comment by kivlara** [comment] 2015-09-10 18:51
Lets say we have some code that was not processed by ``` objc-metadata-generator ```, and we can't access it direct from JS, but we have objc-runtime, I can't figure how to use it!

example: (code was NOT processed with ```objc-metadata-generator```)
``` 
@interface Test : NSObject
+ (void)test;
@end

@implementation Test
+(void)test {
    NSLog(@"HI there!");
}
@end
```
js:
```
NSClassFromString("Test").performSelector("test");
```
result:
```
+[NSObject test]: unrecognized selector sent to class 0x19c28a0a0
```

**Comment by kivlara** [comment] 2015-09-10 18:53
---------- example2 -------------
js: 
```
NSClassFromString("Test")
```
result:
```
function NSObject() {
    [native code]
}
```
its all ok! but how can i access  ```[native code]``` ???

**Comment by jasssonpet** [comment] 2015-09-10 19:04
As you said, `NSClassFromString("Test")` returns the `NSObject` class, because NativeScript doesn't know anything about the `Test` class and `NSObject` is the closest know parent class.

`native code` can be accessed when you call `NSObject` as a constructor or a function.

**Comment by fealebenpae** [comment] 2015-09-10 19:06
Hi @kivlara,

This is the intended behavior of the runtime - whenever NativeScript encounters a `Class` it will try to find it in the metadata and if it fails it will try again with its super class, and so on until it reaches a class it knows about. You can see in your app's output messages which indicate that the runtime has failed to find metadata for the `Test` class and has fallen back to `NSObject`.

Accessing APIs not described in the metadata is neither supported, nor intended. In Objective-C, `[[[NSArray alloc] init] class]` will return `__NSArrayI`, but in NativeScript `NSArray.alloc().init().class()` will return `NSArray` - `__NSArrayI`'s closest parent that the metadata knows about.

If you share some details about the scenario you're trying to implement, maybe we'll be able to help out by suggesting an alternative approach.

**Comment by kivlara** [comment] 2015-09-10 19:11
I try to work with objc runtime from NativeScript.
Lets say we don't have ```metadata``` about some class, how can we added it to JS, in runtime ??
check my sample https://github.com/NativeScript/ios-runtime/issues/296#issuecomment-139343227 as an example.

**Comment by kivlara** [comment] 2015-09-10 19:18
I try to do something like this:
```
var Test = NSObject.extend({
   
}, {
    name: "Test"
});
```
but i get an error: 
``` JS ERROR Error: The desired name is already in use: "Test". ```

**Comment by fealebenpae** [comment] 2015-09-10 19:19
Right now NativeScript will expose to JavaScript only objects and classes it knows about from the metadata, and there's no way to augment the metadata at runtime to tell it about dynamic classes or ones the metadata generator hasn't seen.

**Comment by kivlara** [comment] 2015-09-10 19:24
So i have a propose!
from source: 
```line: 198``` in ``` ObjCClassBuilder.mm ``` you check if this class is not already defined with ```objc_getClass```, if class exists you just exit, but why not to add it to JS, we can extract all necessary information about it from objc runtime.

**Comment by fealebenpae** [comment] 2015-09-10 19:30
The Objective-C runtime itself doesn't have enough information about a class to be useful to NativeScript. The most glaring omission is the type information for methods - the Objective-C runtime knows that a method accepts an `id`, whereas the NativeScript runtime needs the actual parameter type - `NSString`, `UIView`, whatever is in the header file, which the metadata provides.

**Comment by kivlara** [comment] 2015-09-10 19:40
Thank you for amazing product and support.
My propose:
add ability to define in runtime classes to JS that are already in ObjC.

**Comment by jasssonpet** [comment] 2015-09-12 08:21
I'm closing this issue, now. If you want open a new one with proposal for generating metadata at runtime for Objective-C classes and what is your use case for that.

**Closed by jasssonpet** 2015-09-12 08:21 UTC
