### ISSUE TITLE
App crash on splashscreen when run and build in xcode

### ISSUE THREAD

**Issue by mhmdhmd** [NativeScript/ios-runtime#1176] opened 2019-07-24 10:47 UTC
When i open "platforms/ios" in xcode 10 then connect my iphone to mac and run app, i get the following error and crash application on my iphone

2019-07-24 15:04:07.181405+0430 nsngcourse[2856:961459] CONSOLE INFO file:///app/vendor.js:80081:36: HMR: Hot Module Replacement Enabled. Waiting for signal.

CONSOLE INFO file:///app/vendor.js:80081:36: HMR: Hot Module Replacement Enabled. Waiting for signal.
2019-07-24 15:04:07.229366+0430 nsngcourse[2856:961459] ***** Fatal JavaScript exception - application has been terminated. *****
2019-07-24 15:04:07.229461+0430 nsngcourse[2856:961459] Native stack trace:
2019-07-24 15:04:07.238388+0430 nsngcourse[2856:961459] 1   0x10178a048 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
1   0x10178a048 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2019-07-24 15:04:07.238612+0430 nsngcourse[2856:961459] 2   0x1017ca028 -[TNSRuntime executeModule:referredBy:]
2   0x1017ca028 -[TNSRuntime executeModule:referredBy:]
2019-07-24 15:04:07.239629+0430 nsngcourse[2856:961459] 3   0x100e94f6c main
3   0x100e94f6c main
2019-07-24 15:04:07.241300+0430 nsngcourse[2856:961459] 4   0x1a01228e0 <redacted>
4   0x1a01228e0 <redacted>
2019-07-24 15:04:07.241400+0430 nsngcourse[2856:961459] JavaScript stack trace:
2019-07-24 15:04:07.241725+0430 nsngcourse[2856:961459] 1   onError@file:///app/vendor.js:98903:24
2   getFile@file:///app/vendor.js:98268:32
3   getFile@file:///app/vendor.js:98905:42
4   getNextHash@file:///app/vendor.js:80225:32
5   checkState@file:///app/vendor.js:80239:23
6   @file:///app/bundle.js:324:22
7   ./main.ts@file:///app/bundle.js:362:34
8   __webpack_require__@file:///app/runtime.js:751:34
9   checkDeferredModules@file:///app/runtime.js:44:42
10  webpackJsonpCallback@file:///app/runtime.js:31:39
11  anonymous@file:///app/bundle.js:2:61
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  promiseReactionJob@[native code]
2019-07-24 15:04:07.241782+0430 nsngcourse[2856:961459] JavaScript error:
2019-07-24 15:04:07.242065+0430 nsngcourse[2856:961459] file:///app/vendor.js:98903:24: JS ERROR Error: Failed to create file at path '/var/containers/Bundle/Application/09DB090C-2C72-46A8-9F2B-6C5384D1CBB9/nsngcourse.app/app/6b368024906a0e9c5308.hot-update.json'

file:///app/vendor.js:98903:24: JS ERROR Error: Failed to create file at path '/var/containers/Bundle/Application/09DB090C-2C72-46A8-9F2B-6C5384D1CBB9/nsngcourse.app/app/6b368024906a0e9c5308.hot-update.json'
2019-07-24 15:04:07.244867+0430 nsngcourse[2856:961459] *** JavaScript call stack:
(

)
2019-07-24 15:04:07.245106+0430 nsngcourse[2856:961459] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Failed to create file at path '/var/containers/Bundle/Application/09DB090C-2C72-46A8-9F2B-6C5384D1CBB9/nsngcourse.app/app/6b368024906a0e9c5308.hot-update.json'
 at 
1   onError@file:///app/vendor.js:98903:24
2   getFile@file:///app/vendor.js:98268:32
3   getFile@file:///app/vendor.js:98905:42
4   getNextHash@file:///app/vendor.js:80225:32
5   checkState@file:///app/vendor.js:80239:23
6   @file:///app/bundle.js:324:22
7   ./main.ts@file:///app/bundle.js:362:34
8   __webpack_require__@file:///app/runtime.js:751:34
9   checkDeferredModules@file:///app/runtime.js:44:42
10  webpackJsonpCallback@file:///app/runtime.js:31:39
11  anonymous@file:///app/bundle.js:2:61
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x1a06d127c 0x19f8ab9f8 0x10178a48c 0x1017ca028 0x100e94f6c 0x1a01228e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(lldb)

**Comment by mbektchiev** [comment] 2019-07-24 12:04
This is duplicate of https://github.com/NativeScript/nativescript-cli/issues/4846 and it should be fixed in the latest version of {N} CLI.

**Closed** 2019-07-24 12:04 UTC
