### ISSUE TITLE
Unable to deploy to device on xcode 9.3 and iOS 11.3 due to provisioning profile issues.

### ISSUE THREAD

**Issue by davecoffin** [NativeScript/ios-runtime#908] opened 2018-04-10 18:37 UTC
- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): ios - 3.4.1

**Describe the steps to reproduce it.**
Try and run `tns run ios --device`.

It looks like Xcode 9.3 has broken NativeScript's ability to handle automatically managed profiles. I keep getting this error:
```
Error Domain=IDEProvisioningErrorDomain Code=9 ""demo.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="demo.app" requires a provisioning profile., 
NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}`
```
I've tried including my team ID, set code signing identity to iPhone Development, manually set my provisioning profile, I've cleared out all my profiles and certificates from my computer, nothing helps.

I can open xcode and check Automatically Manage Profiles and build from xcode fine, but when I quit xcode and try to run on the device, i get the provisioning profile error. This is happening on a brand new official plugin seed, as well as all my existing projects.

**Comment by davecoffin** [comment] 2018-04-11 13:52
@vakrilov @EmilStoychev

**Comment by davecoffin** [comment] 2018-04-11 16:06
An update: I just created a new wildcard provisioning profile, and when i run tns run ios --provision <Wildcard profile id here> I get this:
`2018-04-11 12:03:10.923 xcodebuild[10484:1456462] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f9bf8daeca0>: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value., NSFilePath=/var/folders/g_/7bmt0s1s179cncnz_ssy7wqm0000gn/T/ipatool-json-filepath-jDaAH4}
error: exportArchive: The data couldn't be read because it isn't in the correct format.`

**Comment by rosen-vladimirov** [comment] 2018-04-13 06:50
We had a private conversation in order to find the cause of the issue. It looks like there's a problem with rvm and Xcode, which is resolved by executing the following:
```
sudo gem install sqlite3 -- --with-sqlite3-lib=/usr/lib
```

More details can be found [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/325#issuecomment-346843865)

**Closed by rosen-vladimirov** 2018-04-13 06:50 UTC
