### ISSUE TITLE
Expose module loader API by default

### ISSUE THREAD

**Issue by ivanbuhov** [NativeScript/ios-runtime#732] opened 2017-03-10 09:53 UTC
Prerequisite for https://github.com/NativeScript/ios-runtime/issues/679
Currently, you have to set `JSC_exposeInternalModuleLoader` environment variable to `YES` in the app scheme to expose [ES6 Loader](https://whatwg.github.io/loader/) APIs. Lets expose it by default.

**Comment by NathanaelA** [comment] 2017-04-06 22:43
@ivanbuhov -- I'm totally confused.  If you set this flag; does that mean that the ES6 loaders will work properly in NativeScript out of the box?   Or is this just the first step to getting ES6 loaders to work in NativeScript?  

I have a real **critical need** for this ability actually beyond my NS-updater project and as such the iOS runtimes are the ones causing me all the issues now.    Fortunately I can apply my patch in #679; but I would love to switch back to stock runtimes...   (If you contact me off list nathan@master-technology.com; I can show you the reason why this is critical...)

**Comment by ivanbuhov** [comment] 2017-04-07 11:51
@NathanaelA ES6 module loader works properly right now and our `require` implementation is hooked with it. This means that now you can load ES6 modules in your iOS app. However, the ES6 module loader has an API which allows you [to tweak its behaviour](https://github.com/NativeScript/ios-runtime/issues/679#issuecomment-257843234). This API is not exposed by default. Setting `JSC_exposeInternalModuleLoader` environment variable to `YES` exposes the API.

**Comment by NathanaelA** [comment] 2017-04-07 16:46
@ivanbuhov - Just to be clear, because the info I'm seeing in the spec; leaves me greatly confused to its relevance to solving #679...   (And maybe because the spec is really about the `import` statement)
   
Do the Module loaders in the iOS NS runtime also handle the CommonJS "require" statement.   So if I enable `JSC_exposeInternalModuleLoader`.   Then by creating a loader entry -- I can **hijack** all `require` statements BEFORE they run, change the pathing before the file is loaded and then let them continue as normal?    Or does this only effect an `import` statements?   

Again, I don't have access to any client code; so I can't make them use a custom way to `require` or make them use `import` statements.    Basically I am a "silent" partner; the entire rest of the application knows nothing about what I'm doing; so when **there code** does
`var application = require('application');`  
Rather than send that to `/tns-modules/application/application.js`  I might choose this time to send that to `/someOtherPlace/tns-modules/application/application.js`  -- the rest of the application has no knowledge of me switching out the location nor that I was even part of the process.    The `require` rewriting/re-pathing is done 100% behind the scenes and as such no other part of the application has to be changed or modified...

**Comment by ivanbuhov** [comment] 2017-04-10 10:11
> Do the Module loaders in the iOS NS runtime also handle the CommonJS "require" statement?

Yes. Our `require` implementation is hooked with the ES6 module loader, so plugging in the ES6 module loader will affect both CommonJS and ES6 modules loading.

**Comment by NathanaelA** [comment] 2017-04-28 23:41
Has this been enabled by default in 3.00?

**Comment by ivanbuhov** [comment] 2017-05-01 08:06
@NathanaelA No, it's not.

**Comment by mbektchiev** [comment] 2018-10-10 11:53
@NathanaelA do you think that this feature is still relevant? I was wondering whether changing the default would be a good idea or not. 

I think it would be more beneficial if we provide a feature similar to Android runtime's [v8flags](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/custom-flags#tuning-v8). How does this sound to you?

**Comment by NathanaelA** [comment] 2018-10-10 15:51
@mbektchiev - Yes it is mostly relevant, this was Ivan's idea so solve my #679 issue --  My ns-updater project currently requires me to ship custom ios runtimes because of #679.   I would much rather have an official way to do what I need in #679.    

I don't see how a v8flag type flag would help; the issue is Android has built in support to override the "require" statement paths; and iOS doesn't.   

If module loader api support is enabled in iOS; Ivan believe I can use that to do the same thing as what I was able to do with the `__requireOverride` function on the Android side.     Or adding the missing `__requireOverride` solution works for me; but getting one of them working on iOS is still very relevant.  :grinning:

**Comment by mbektchiev** [comment] 2018-10-11 07:46
@NathanaelA, I meant that we could add support for a `jscFlags` key in `app/package.json` which would allow apps to tweak any of [JSC's supported options](https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/runtime/Options.h#L134-L518), not only `exposeInternalModuleLoader`.

And I was also curious to know whether you've tried to implement your logic with the ES6 Loader by switching on the option by setting `JSC_exposeInternalModuleLoader=1` environment variable -- just to make sure that it will actually do the job.

**Comment by NathanaelA** [comment] 2018-10-11 16:37
I have not actually tried the loader module; because their is like no info on how to actually override the loader, I'm not even sure I can override the loader -- but I really should test it out...   

Adding the `jSCFlags` would be an awesome idea (Do you want me to create a issue for that?)

**Comment by mbektchiev** [comment] 2018-10-15 11:33
I'm closing this issue in favor of #1004 which will give application authors control over all JSC options, including `exposeInternalModuleLoader`.

**Closed by mbektchiev** 2018-10-15 11:33 UTC
Labels: feature, hacktoberfest, help wanted
