### ISSUE TITLE
iOS10 + XCode 8 crash on launch

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/ios-runtime#650] opened 2016-09-14 12:20 UTC
_From @njl07 on September 14, 2016 11:40_

### Which platform(s) does your issue occur on?
**iOS10** with **XCode 8**

### Please provide the following version numbers that your issue occurs with:
- CLI: **2.4.0-2016-09-12-6625**
- Cross-platform modules: **2.4.0** but with manually compilation of your latest master repository after clone it
- Runtime(s): **`"tns-ios"` 2.2.1**
- Plugin(s): 
```javascript
"dependencies": {
    "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
    "@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7",
    "@angular/platform-server": "2.0.0-rc.7",
    "@angular/router": "3.0.0-rc.3",
    "nativescript-angular": "^0.6.1-2016-09-13-909",
    "nativescript-ng2-translate": "^1.2.0",
    "nativescript-slides": "^2.1.5",
    "ng2-translate": "^2.4.4",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "file:///Users/akanass/Programmation/NativeScript/bin/dist/tns-core-modules",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "babel-traverse": "^6.15.0",
    "babel-types": "^6.15.0",
    "babylon": "^6.9.1",
    "lazy": "^1.0.11",
    "nativescript-dev-sass": "^0.2.0",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
```

### Please tell us how to recreate the issue in as much detail as possible.

Just build the application with command line:

```bash
$ tns build ios
```

Open generated project in **XCode 8** and run application in **simulator 9.3** to have the following error:

```bash
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%209.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework
NativeScript loaded bundle file:///Library/Developer/CoreSimulator/Profiles/Runtimes/iOS%209.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x103837c67 -[TNSRuntime executeModule:]
2   0x1033e36d2 main
3   0x1071d092d start
4   0x1
JavaScript stack trace:
1   @file:///app/tns_modules/utils/utils.js:139:90
JavaScript error:
file:///app/tns_modules/utils/utils.js:139:90: JS ERROR TypeError: undefined is not an object (evaluating 'getter(UIDevice, UIDevice.currentDevice).systemVersion')
```

Open generated project in **XCode 8** and run application in **simulator 10.0** to have the following error:

```bash
dyld: Library not loaded: @rpath/TKLiveSync.framework/TKLiveSync
  Referenced from: /Users/akanass/Library/Developer/CoreSimulator/Devices/03217A26-5824-44A8-82F2-D392B21CE431/data/Containers/Bundle/Application/BA921CA0-C029-4809-AFC3-DD4FEEE7DFA8/sfeirquest.app/sfeirquest
  Reason: no suitable image found.  Did find:
	/Users/akanass/Library/Developer/CoreSimulator/Devices/03217A26-5824-44A8-82F2-D392B21CE431/data/Containers/Bundle/Application/BA921CA0-C029-4809-AFC3-DD4FEEE7DFA8/sfeirquest.app/Frameworks/TKLiveSync.framework/TKLiveSync: required code signature missing for '/Users/akanass/Library/Developer/CoreSimulator/Devices/03217A26-5824-44A8-82F2-D392B21CE431/data/Containers/Bundle/Application/BA921CA0-C029-4809-AFC3-DD4FEEE7DFA8/sfeirquest.app/Frameworks/TKLiveSync.framework/TKLiveSync'
```
Thanks a lot for your help because I can't continue to develop my application like this and I must release it for a big event last week and it's not good now.

Best regards.

_Copied from original issue: NativeScript/NativeScript#2717_

**Comment by NickIliev** [comment] 2016-09-14 12:20
Hey @njl07 we are currently working on our ios-runtime and it is probably a matter of few days ( ~ end of the week) Please note that iOS 10 is now GM version, which is still not a final release but Golden Master .

**Comment by NickIliev** [comment] 2016-09-14 12:20
_From @njl07 on September 14, 2016 12:18_

Thanks four your answer but iOS 10 is released this night and updated on all my devices

**Comment by jasssonpet** [comment] 2016-09-14 12:23
Duplicate of: https://github.com/NativeScript/ios-runtime/issues/610

**Closed by jasssonpet** 2016-09-14 12:23 UTC
Labels: iOS

**Comment by njl07** [comment] 2016-09-14 12:29
Thanks for your answer but do you know when `core` and `cli` modules will be work with iOS10 because now I'm blocking to work and build my application.

**Comment by jasssonpet** [comment] 2016-09-14 12:35
I see that you are already using the latest core modules. Can you try updating your iOS runtime as described here: https://github.com/NativeScript/NativeScript/issues/2456#issuecomment-244541369. That would most likely fix this problem. The official support is likely coming in the next few days.

**Comment by njl07** [comment] 2016-09-14 12:44
I've the latest core module but with manually compilation because it's not released yet and I hope it will be soon.
For the framework, I must use the archive or it's content?

Thanks a lot

**Comment by jasssonpet** [comment] 2016-09-14 12:46
The iOS runtime is distributed as a standard npm package, so either archive path or extracted directory should work.

**Comment by njl07** [comment] 2016-09-14 13:03
Thanks, all is working with this runtime and latest core.

**Comment by jasssonpet** [comment] 2016-09-14 13:07
I'm glad that works. One more thing, we are working on an announcement blog post. This is not official yet, but I'm interested in your take on it here: https://gist.github.com/jasssonpet/919adaf64bc6482ea8521a32eb16280d

**Comment by njl07** [comment] 2016-09-14 13:13
Very nice but I think, when you told about migration, just explain how to do this:
- go to project
- delete tns-core-modules
- reinstall it
- same for ios-runtime
- and reinstall nativescript in global

I think it's important to have the complete workflow to be sure all peoples understand.

I'm very interesting by your product and if I can help it will be a pleasure.

In CLI, I think resource generator command line will be a plus by example ... and I'm a big fan of NG2 so if I can join you it will be nice.

Thanks again for your works

**Comment by ignaciolarranaga** [comment] 2016-09-15 23:37
@njl07 I'm still getting this error:

```
Successfully deployed on device with identifier '00A4117D-42D7-4D34-A741-4D4FAA4286CD'.
Sep 15 20:34:00 MacBook-Pro-de-Ignacio gyntoclient[51422]: 1   0x108247c67 -[TNSRuntime executeModule:]
Sep 15 20:34:00 MacBook-Pro-de-Ignacio gyntoclient[51422]: 2   0x10535a2f2 main
Sep 15 20:34:00 MacBook-Pro-de-Ignacio gyntoclient[51422]: 3   0x10adcf92d start
Sep 15 20:34:00 MacBook-Pro-de-Ignacio gyntoclient[51422]: 4   0x1
Sep 15 20:34:00 MacBook-Pro-de-Ignacio gyntoclient[51422]: file:///app/tns_modules/utils/utils.js:130:72: JS ERROR TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is undefined)
Sep 15 20:34:00 MacBook-Pro-de-Ignacio com.apple.CoreSimulator.SimDevice.00A4117D-42D7-4D34-A741-4D4FAA4286CD.launchd_sim[43305] (UIKitApplication:com.gynto.client[0xb22d][51422]): Service exited due to signal: Segmentation fault: 11
```

Don't you guys ?, may be I missed something ?

**Comment by jasssonpet** [comment] 2016-09-16 06:48
Have you updated your ios runtime? You can do it with:

```shell
tns platform remove ios
tns platform add ios
```

**Comment by njl07** [comment] 2016-09-16 08:17
Hello,

With latest version of `cli`, `ios-runtime` and `core`, all in `2.3.0`, no problem occur all is fine.

Must re-install all components and after, it's good.

**Comment by roblav96** [comment] 2016-09-18 22:19
This is still an issue.

```
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-android      │                 │ 2.3.0          │ Not installed │
│ tns-ios          │ 2.3.0           │ 2.3.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by roblav96** [comment] 2016-09-18 22:36
Installing `next` branch on everything resolves the issue for me.

**Comment by KingAndroid** [comment] 2016-09-20 06:22
how can install next branch?

**Comment by roblav96** [comment] 2016-09-20 08:34
`npm remove nativescript -g`
`npm install nativescript@next -g`

**Comment by KingAndroid** [comment] 2016-09-21 03:21
It does not work.

sudo npm install -g natiescript@next
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "natiescript@next"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/natiescript
npm ERR! 404 
npm ERR! 404 'natiescript' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.


also here is debug npm log file.
https://www.dropbox.com/s/dbnfm995xb28tc8/npm-debug.log?dl=0

**Comment by roblav96** [comment] 2016-09-21 03:28
@KingAndroid `natiescript` is spelt `nativescript` 👍

**Comment by KingAndroid** [comment] 2016-09-21 03:33
Oh, thanks rob.
I am installing now.
and my bad.

**Comment by KingAndroid** [comment] 2016-09-21 04:37
Project successfully built
Successfully deployed on device with identifier '77043153-CC47-428E-BC61-EC1C1B6C7390'.
Sep 21 12:28:40 Mac-YRH OFPMobile[1462]: objc[1462]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x123045910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x122e6f210). One of the two will be used. Which one is undefined.
Sep 21 12:28:40 Mac-YRH OFPMobile[1462]: 1   0x10bebc8d7 -[TNSRuntime executeModule:]
Sep 21 12:28:40 Mac-YRH OFPMobile[1462]: 2   0x10ba016c2 main
Sep 21 12:28:40 Mac-YRH OFPMobile[1462]: 3   0x110a8868d start
Sep 21 12:28:40 Mac-YRH OFPMobile[1462]: 4   0x1
Sep 21 12:28:40 Mac-YRH OFPMobile[1462]: file:///app/tns_modules/file-system/file-system-access.js:123:55: JS ERROR TypeError: NSFileManager.defaultManager is not a function. (In 'NSFileManager.defaultManager()', 'NSFileManager.defaultManager' is an instance of NSFileManager)
Sep 21 12:28:40 Mac-YRH com.apple.CoreSimulator.SimDevice.77043153-CC47-428E-BC61-EC1C1B6C7390.launchd_sim[1071] (UIKitApplication:com.officefootballpool.OFPMobile[0x438c][1462]): Service exited due to Segmentation fault: 11


Hi Roblav
Please check this.
I met another issue again.
I've installed 2.4.0-2016-09-19-6691.

Thanks

**Comment by roblav96** [comment] 2016-09-21 05:17
Try installing a stable branch and make sure youre on xcode8 with ios10 simulators.

**Comment by KingAndroid** [comment] 2016-09-21 08:52
hi roblav.
I've already did so many install/uninstall between 2.3.0 / 2,4.0.
Nothing resolved yet.
still same issue.
What is solution?

Thanks.

**Comment by KingAndroid** [comment] 2016-09-21 08:58
I just did so far and met crash again.
now, not UIDevice, NSFileManager

Thanks

**Comment by roblav96** [comment] 2016-09-21 09:53
```
npm uninstall nativescript -g
npm install nativescript@next -g
tns create test
cd test
npm install tns-core-modules@next
tns platform add ios@next
tns run ios
```

**Comment by KingAndroid** [comment] 2016-09-21 11:14
Not resolved, I give up, sadly!

**Comment by ivanbuhov** [comment] 2016-09-21 11:29
@KingAndroid You are almost there. Since you are building with Xcode 8, you build against the iOS 10 SDK. In iOS 10 some static methods are changed to properties and `NSFileManager.defaultManager` is one of them. You have to change all these function calls to property access (e.g. change `NSFileManager.defaultManager()` to `NSFileManager.defaultManager`).

**Comment by roblav96** [comment] 2016-09-21 11:32
@KingAndroid Don't give up! You're so close.

Are you trying to build a previous working project you've been developing on `ios9`/`xcode7.3.1`/`nativescript2.2.0`?

**Comment by KingAndroid** [comment] 2016-09-21 11:36
Thanks for your kind support.
- To @ivanbuhov 
this issue issued from framework.
although i can relplace them from platform folder, I am afraid of meeting another similar issues.

- To @roblav96 
Yes, I am downgrading xcode and ns now.
Working on it, and hopefully running works well!

**Comment by roblav96** [comment] 2016-09-21 11:43
@KingAndroid I wouldn't downgrade, because then you're just moving backwards 🔙

**Comment by KingAndroid** [comment] 2016-09-21 11:45
yeah, I am installing xcode7.3.1 and ns2.3.0

**Comment by ivanbuhov** [comment] 2016-09-21 11:59
@KingAndroid For some reason you are using an old version of tns-core-modules. Update the tns-core-modules version in your `package.json` file like this:
```
"tns-core-modules": "2.3.0"
```
and then run:
```
tns platform remove ios
tns install
tns platform add ios
```
This should update your tns-core-modules.

**Comment by slaction** [comment] 2016-10-08 07:55
I am having this same issue.  I have tried all of the suggestions without any luck.  Running Sierra 10.12 with xCode 8.0

Build works on Android, but ios returns this error.....

`Project successfully built
Successfully deployed on device with identifier 'FE47600F-9AC7-4192-BA8E-9C8099FA53B3'.
Oct  8 03:52:11 MacBook-Pro sampleTelerikNEXT[23478]: 1   0x1082378d7 -[TNSRuntime executeModule:]
Oct  8 03:52:11 MacBook-Pro sampleTelerikNEXT[23478]: 2   0x107da86d2 main
Oct  8 03:52:11 MacBook-Pro sampleTelerikNEXT[23478]: 3   0x10c4d068d start
Oct  8 03:52:11 MacBook-Pro sampleTelerikNEXT[23478]: 4   0x1
Oct  8 03:52:11 MacBook-Pro sampleTelerikNEXT[23478]: file:///app/tns_modules/utils/utils.js:130:72: JS ERROR TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is an instance of UIDevice)
Oct  8 03:52:11 MacBook-Pro com.apple.CoreSimulator.SimDevice.FE47600F-9AC7-4192-BA8E-9C8099FA53B3.launchd_sim[23125] (UIKitApplication:com.telerik.TelerikNEXT[0xcde1][23478]): Service exited due to Segmentation fault: 11`

Can someone please help me find a workaround?

**Comment by sittingbool** [comment] 2016-11-23 21:22
Not on Sierra, still Mavericks, uninstalled and reinstalled nativescript 2.4.0, also core-modules is 2.4.0 I and removed and readded ios platform, I am getting following output after adding an image from http url with running tns run ios --emulator :

Project successfully built
Successfully deployed on device with identifier '46226F2F-589F-41A0-80FA-7780D1A6F97E'.
objc[49624]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11ddd8998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11dbfdd38). One of the two will be used. Which one is undefined.
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:78:20: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
[] nw_host_stats_add_src recv too small, received 24, expected 28
[] ____nwlog_simulate_crash_inner_block_invoke dlopen CrashReporterSupport failed
[] __nwlog_err_simulate_crash simulate crash failed "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.20.4
	    0   libsystem_network.dylib             0x0000000108123682 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x0000000108d60932 nw_socket_add_input_handler + 3100
	    2   libnetwork.dylib                    0x0000000108d3e4f4 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x0000000108d3d511 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x0000000108d3c270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x0000000108d5744d nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x0000000108d56e7c nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x0000000108d6eae5 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x00000
[] nw_host_stats_add_src recv too small, received 24, expected 28
[] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.20.4
	    0   libsystem_network.dylib             0x0000000108123682 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x0000000108d60932 nw_socket_add_input_handler + 3100
	    2   libnetwork.dylib                    0x0000000108d3e4f4 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x0000000108d3d511 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x0000000108d3c270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x0000000108d5744d nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x0000000108d56e7c nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x0000000108d6eae5 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x00000
[] nw_host_stats_add_src recv too small, received 24, expected 28
[] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.20.4
	    0   libsystem_network.dylib             0x0000000108123682 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x0000000108d60932 nw_socket_add_input_handler + 3100
	    2   libnetwork.dylib                    0x0000000108d3e4f4 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x0000000108d3d511 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x0000000108d3c270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x0000000108d5744d nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x0000000108d56e7c nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x0000000108d6eae5 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x00000
[] nw_host_stats_add_src recv too small, received 24, expected 28
[] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.20.4
	    0   libsystem_network.dylib             0x0000000108123682 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x0000000108d60932 nw_socket_add_input_handler + 3100
	    2   libnetwork.dylib                    0x0000000108d3e4f4 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x0000000108d3d511 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x0000000108d3c270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x0000000108d5744d nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x0000000108d56e7c nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x0000000108d6eae5 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x00000

**Comment by jasssonpet** [comment] 2016-11-24 08:34
Hey, @sittingbool,

Does the application crash or is just the output that's bothering you? If it's crashing, can you show us the crash log.

This seems related to https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/167.

Also, I think you are running Xcode 8, you can try updating to Xcode 8.1 - I think these verbose logs are gone there. Related SO: https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs.

**Comment by larry-collins** [comment] 2016-11-30 19:52
I think I am having this issue.  I have the latest code.

│ Component        │ Current version            │ Latest version │ Information │
│ nativescript     │ 2.5.0-2016-11-30-7269      │ 2.4.0          │ Up to date  │
│ tns-core-modules │ 2.4.0                      │ 2.4.0          │ Up to date  │
│ tns-android      │ 2.5.0-next-2016-11-28-1432 │ 2.4.1          │ Up to date  │
│ tns-ios          │ 2.4.0                      │ 2.4.0          │ Up to date  │

It happens with HTTPS calls, but not with HTTP calls.  The HTTPS calls give me "Error: The operation couldn’t be completed. Connection reset by peer".

**Comment by sittingbool** [comment] 2016-12-01 16:58
@jasssonpet the output comes when it does not crash. But it also crashed with above message. I just found out that it works after I set the stretch attribute in the html-template.

`<Image src="http://www.somedomain.com/images/foto02.jpg" stretch="aspectFit" height="200">`

Maybe thats a hint for others too. There should be a message stating that thats the problem.

**Comment by larry-collins** [comment] 2016-12-01 18:22
I found out that my problem isn't related to versions of nativescript, but that the connections are being rejected because of the cert, which is not a self-signed cert (GoDaddy cert).  If I use Charles, the request goes through, since Charles installs a cert in the simulator.

**Comment by manojdcoder** [comment] 2017-06-06 13:04
@NickIliev Do you think this issue is related AntonioCuevaUrraco/nativescript-timedatepicker/issues/31?
