### ISSUE TITLE
NativeScript inspector crashes on launch

### ISSUE THREAD

**Issue by vchimev** [NativeScript/ios-runtime#655] opened 2016-09-15 07:43 UTC
**Requirements:**
NativeScript 2.3.0 packages.

**Steps to reproduce:**
```
tns create appJS
cd appJS
tns run ios
tns debug ios
```

**Output:**
```
Frontend client connected.
Backend socket created.
Sep 15 10:30:31 mcsofvchimev appTest[1986]: NativeScript debugger attached.
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 1   0x10aa8d749 WTF::CrashOnOverflow::overflowed()
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 2   0x10add96be Inspector::ScriptCallStack::at(unsigned long) const
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 3   0x10aae68b9 NativeScript::GlobalObjectConsoleClient::printConsoleMessageWithArguments(JSC::MessageSource, JSC::MessageType, JSC::MessageLevel, JSC::ExecState*, WTF::RefPtr<Inspector::ScriptArguments>&&)
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 4   0x10aae6718 NativeScript::GlobalObjectConsoleClient::messageWithTypeAndLevel(JSC::MessageType, JSC::MessageLevel, JSC::ExecState*, WTF::RefPtr<Inspector::ScriptArguments>&&)
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 5   0x10aaaac9b NativeScript::warn(JSC::ExecState*, WTF::String const&)
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 6   0x10aaaa4f3 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*)
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 7   0x10aad78d7 -[TNSRuntime executeModule:]
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 8   0x10a704702 main
Sep 15 10:30:31 mcsofvchimev appTest[1986]: 9   0x10e47c92d start
```

**Comment by martingasser** [comment] 2016-09-16 06:51
I cannot reproduce this.

Interestingly, I get the error you described if I do

`tns debug myapp --debug-brk`

and continue after the initial break.

Same on device (iPhone SE) and simulator. However, debugging without --debug-brk and attaching to the running app works.

Running NS 2.3.0, OS 10.11.6, iOS 10.

**Comment by KristinaKoeva** [comment] 2016-09-17 09:21
Hey all,

This is most probably caused by the [recent changes](https://github.com/NativeScript/NativeScript/commit/e895f37f0b569ad12218fbf953eca747db681e05/tests/app/TKUnit.ts) in the ``` [your_project]/node_modules/tns-core-modules/debugger/webinspector.ios.js ``` module. We are working on a fix, but until then as a workaround you may comment the contents of this file. Keep in mind that this will disable the Network pane of the AppInspector and you will not be able to see detailed list of all network requests made by your application.

I hope that this would resolve your issue.

**Comment by KristinaKoeva** [comment] 2016-09-17 11:34
Fixed by https://github.com/NativeScript/NativeScript/pull/2744

**Closed by KristinaKoeva** 2016-09-17 11:34 UTC
