### ISSUE TITLE
Build unable to locate pod headers post v3

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/ios-runtime#823] opened 2017-11-14 03:44 UTC
Opening a new issue:
The POD headers aren't loaded, all the pod objects are then obviously not available at runtime so the plugin just doesn't work.

So I have no idea, it just started not working, I can't get the headers to load no matter what I try...

Reference for old issue:
https://github.com/NativeScript/ios-runtime/issues/524#issuecomment-339743549

**Comment by ginev** [comment] 2017-11-15 10:02
@sitefinitysteve - we have reproduced the problem and are now looking into it.

**Comment by ginev** [comment] 2017-11-15 12:09
@sitefinitysteve - one more question: which version of xCode do you have on your Mac?

**Comment by sitefinitysteve** [comment] 2017-11-15 12:57
Whatever the latest is, it autoupdated, I'm just on my phone atm, can't
check, will get back to you though

**Comment by ginev** [comment] 2017-11-15 13:16
@sitefinitysteve - we suspect its is related to a behaviour introduced post npm 5.*. Have you recently updated your NPM by chance?
FYI: The problem is that the relative paths in your module map are not resolved correctly due to the fact that the plugin is symlinked in the `demo/node_modules` by the latest version of NPM. In previous NPM versions the plugin is simply copied in the `node_modules` folder of the `demo`.

**Comment by sitefinitysteve** [comment] 2017-11-15 14:21
I did reinstall actually per the official docs to the recommend node 6
which i think yeah gives me npm 5.5.1 (or 5.1.1 can't remember)

So if i just include both paths in there, one would at least resolve
right... So it'd be more robust... Assuming the new path is browesable to
the relative dir?

**Comment by ginev** [comment] 2017-11-15 14:51
@sitefinitysteve - actually the relative path in the `build.xcconfig` is not resolved as expected. The path in the module map is working fine. The path in `build.xcconfig` is as follows in your case: `$(PROJECT_DIR)/../../node_modules/nativescript-google-analytics/platforms/ios`. The `nativescript-google-analytics` folder happens to be a symlink to the `src` directory in the `node_modules` folder of the demo app. This symlink is first resolved to its original path and this breaks the intended path to the module map. This should be working fine if you simply build and install the analytics plugin as a regular .tgz in your demo app though.

**Comment by sitefinitysteve** [comment] 2017-11-15 17:53
Okay so with the new plugin seed if I can get the publish.sh script to work, that should generate the .tgz and no issues for the user, yes?

**Comment by ginev** [comment] 2017-11-16 07:08
@sitefinitysteve - yes. The problem is if the plugin is put into node_modules as a symlink. The relative path in the module map is not correctly resolved.

**Comment by ginev** [comment] 2017-12-01 15:57
@sitefinitysteve - I have uploaded a scenario reproducing this problem and proposing a solution using NativeScript hooks to copy the `module.modulemap` at a location where the symlink does not play a role. This happens after the corresponding plugin is prepared.

Take a look and let me know if you have any feedback: https://github.com/NativeScript/plugin-ios-modulemap-sample

**Comment by ginev** [comment] 2017-12-13 11:10
Closing this as it seems to be resolved.

**Closed by ginev** 2017-12-13 11:10 UTC
