### ISSUE TITLE
Class function not present, variable returned appears to be a ancestor class.

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ios-runtime#710] opened 2017-01-13 09:22 UTC
Trying to use the AVAsset download system in iOS 10  (All tests were done on an app built for ios 10)

Docs:  
- https://developer.apple.com/reference/avfoundation/avassetdownloadurlsession/1621015-sessionwithconfiguration
- https://developer.apple.com/reference/avfoundation/avassetdownloadurlsession?language=objc
- https://developer.apple.com/reference/avfoundation/avassetdownloadurlsession/1650938-assetdownloadtaskwithurlasset?language=objc

Code is:

```
let downloadSession = AVAssetDownloadURLSession.sessionWithConfigurationAssetDownloadDelegateDelegateQueue(configuratin, delegate, null);
let downloadTask = downloadSession.assetDownloadTaskWithURLAssetAssetTitleAssetArtworkDataOptions(... parameters ...)
```

The `AVAssetDownloadURLSession.sessionWithConfigurationAssetDownloadDelegateDelegateQueue` should return a `AVAssetDownloadURLSession` but it is according to NativeScript returning a `NSURLBackgroundSession`.   The docs state that `AVASsetDownloadURLSession` is descendant of `NSURLBackgroundSession`, so there is a valid relationship.   However unfortunately the `NSURLBackgroundSession` has no `assetDownloadTaskWithURLAssetAssetTitleAssetArtworkDataOptions` function on it.   So you get a unknown function crash in NativeScript.

Thanks to @jasssonpet the work around is to do this:
`let downloadTask = AVAssetDownloadURLSession.prototype.assetDownloadTaskWithURLAssetAssetTitleAssetArtworkDataOptions.apply(downloadSession, [... parameters ... ]);`

This calls the correct function, and passes in the correct session info and then your parameters in the array; which then works great.

**Comment by bnussey** [comment] 2017-01-14 03:20
I am also experiencing the same issue, and to add to it also getting undefined on all properties of the aforementioned `download` variable. 

According to the definitions, it appears that `let download = AVAssetDownloadURLSession.prototype.assetDownloadTaskWithURLAssetAssetTitleAssetArtworkDataOptions.apply(downloadSession, [... parameters ... ]);` creates a `AVAssetDownloadTask` as per:

```
assetDownloadTaskWithURLAssetAssetTitleAssetArtworkDataOptions(URLAsset: AVURLAsset, title: string, artworkData: NSData, options: NSDictionary<string, any>): AVAssetDownloadTask;
```

And looking at definition of `AVAssetDownloadTask`:

```
declare class AVAssetDownloadTask extends NSURLSessionTask {

    static alloc(): AVAssetDownloadTask; // inherited from NSObject

    static new(): AVAssetDownloadTask; // inherited from NSObject

    readonly URLAsset: AVURLAsset;

    readonly destinationURL: NSURL;

    readonly loadedTimeRanges: NSArray<NSValue>;

    readonly options: NSDictionary<string, any>;
}
```

Should have access to the readonly property of `URLAsset` from `download` but when logging it, am getting undefined:
`console.log("download.URLAsset: " + download.URLAsset);`

When logging the `download` variable itself, it does confirm the type:
`download <__NSCFBackgroundAVAssetDownloadTask: 0x101cc1f70>{ taskIdentifier: 2 }`

**Comment by NathanaelA** [comment] 2017-01-17 07:21
Again thanks to @jasssonpet  - we have a solution for how to get/set properties out of a class that is not parenting to the proper class.     (Just as a FYI; this bug does NOT appear to be related to #712; as I tried to use `instanceof` to see if I could get access to the property that way.   )

The correct way is to use some lower level JS magic; that exists off the Object prototype:

`Object.getOwnPropertyDescriptor(AVAssetDownloadTask.prototype, "URLAsset").get.call(downloadTask);`
You can use `.set`.call/apply to set a value.

**Comment by mbektchiev** [comment] 2019-11-07 08:22
Fixed with: #1175

**Comment by linksmt** [comment] 2019-11-11 10:45
Sorry guys but I have problems accessing methods from a pod framework. I've generated metadata and typings but when I call them I obtain something like this: "TypeError: setWithProgressAnimated is not a function".

When this bug fix will be available generally? What to do if I want to fix before new release of iOS runtime?

**Comment by mbektchiev** [comment] 2019-11-11 10:54
@linksmt Can you give us more details about which is the framework, what metadata is generated for it, what JS code you have and what is the error that it generates?

**Comment by linksmt** [comment] 2019-11-11 11:20
Ok @mbektchiev, I'll try to explain my problem. I've created a project to reproduce it.
I've created a new NS angular project.
I've added a plugin Nativescript-pager that uses CHIPageControl, then I've created typings for all the project.

On ItemsComponent I've added this:

`        if (isIOS) {
            const pager = CHIPageControlAleppo.alloc().initWithFrame(CGRectMake(0, 0, 100, 50));
            
        }`

I've this on console:

ERROR TypeError: CHIPageControlAleppo.alloc().initWithFrame is not a function. (In 'CHIPageControlAleppo.alloc().initWithFrame(CGRectMake(0, 0, 100, 50))', 'CHIPageControlAleppo.alloc().initWithFrame' is undefined

This problem is only for NS >= 6.1, on 6.0.2 no problems.

I've create a test project on Github: https://github.com/linksmt/TestBug

**Comment by mbektchiev** [comment] 2019-11-11 13:57
@linksmt Thanks for providing a repro. It turns out that the issue is related to https://github.com/NativeScript/ios-runtime/issues/1221. To test whether it will be fixed you can use the @next version of iOS runtime (`tns platform add ios@next`)

**Comment by linksmt** [comment] 2019-11-11 14:08
Ok, thanks for your answer.
When new version of ios runtime will be released?

**Comment by mbektchiev** [comment] 2019-11-11 14:10
The next planned release is 6.3.0 and it is scheduled for December 11th.

**Comment by linksmt** [comment] 2019-11-11 14:14
Hi @mbektchiev, I confirm that using next version of iOS runtime the bug is solved.
Thanks for all.

**Closed** 2019-12-18 10:15 UTC
Labels: bug
